name: Build

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on: [push]

jobs:
    build:
      runs-on: "ubuntu-20.04.3"
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '1.23.2' # The Go version to download (if necessary) and use.
        - run: |
            go version
            go mod tidy
            go build main.go
        - uses: actions/upload-artifact@v4
          with: 
            overwrite: true
            path: main

